baseURL = "https://juliangerber.de/"
languageCode = "de-de"
theme = "theme"
[[menu.footer]]
URL = "#portfolio"
name = "Datenschutz"
weight = 2
[[menu.header]]
URL = "#contact"
name = "Kontakt"
weight = 3
[[menu.header]]
URL = "#portfolio"
name = "Projekte"
weight = 2
[[menu.header]]
URL = "#about"
name = "Über mich"
weight = 1
[params]
googleTagManagerID = "GTM-WHXP3DF"
sections = ["showcase", "about", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter"]
[params.footer]
copyright = "© 2021 - Alle Rechte vorbehalten"
[params.footer.radity_logo]
_2x = "img/general/logo-footer@2x.png"
alt = "Julian Gerber"
x = "img/general/logo-footer.png"
[params.logo]
text1 = "Julian Gerber"
text2 = "Ofizielle Website"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/rad-icons.css"
[[params.plugins.css]]
URL = "css/custom.css"
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"
[[params.plugins.js]]
URL = "js/library/fontfaceobserver.js"
